const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/root/.local/share/gstack/node_modules/playwright');
const fs=require('fs'),path=require('path');
const out=path.resolve(__dirname,'../records/browser-replay','two-rounds-'+Date.now());fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1080},recordVideo:{dir:out,size:{width:1440,height:1080}}});
const p=await context.newPage(),log={errors:[],rounds:[],requests:[],responses:[]},pending=[];
p.on('pageerror',e=>log.errors.push(e.message));p.on('request',r=>{if(r.url().includes('/api/')&&r.method()==='POST')log.requests.push({url:r.url(),body:r.postDataJSON()})});p.on('response',r=>{if(r.url().includes('/api/')&&r.request().method()==='POST')pending.push(r.json().then(body=>log.responses.push({url:r.url(),status:r.status(),body})).catch(()=>{}))});
async function play(){await p.locator('#reset-play').click();const box=await p.locator('#stage').boundingBox();const move=x=>p.mouse.move(box.x+x*box.width,box.y+.55*box.height);await move(.18);await p.mouse.down();for(let x=.185;x<=.54;x+=.005){await p.waitForTimeout(45);await move(x)}await p.waitForTimeout(20);await move(.8);await p.mouse.up();}
async function ask(text,round){await p.locator('#intent').fill(text);const response=p.waitForResponse(r=>r.url().endsWith('/api/intent'),{timeout:120000});await p.locator('#generate').click();const r=await response,candidate=await r.json();if(!r.ok()||candidate.status!=='proposed')throw new Error('No candidate: '+JSON.stringify(candidate));await p.waitForFunction(()=>!document.querySelector('#try-new').disabled);await p.waitForFunction(()=>document.querySelector('#message').textContent.startsWith('Same recorded play replayed'));
await Promise.all(pending);const req=log.requests.filter(r=>r.url.endsWith('/replay')).slice(-2),res=log.responses.filter(r=>r.url.endsWith('/replay')).slice(-2);const cargo=res.map(r=>r.body.final.objects.B.x);const proof={intent:text,base_version:candidate.base_version,candidate:candidate.rules,identicalInput:JSON.stringify(req[0].body.frames)===JSON.stringify(req[1].body.frames),identicalInitial:JSON.stringify(req[0].body.initial)===JSON.stringify(req[1].body.initial),cargo};if(!proof.identicalInput||!proof.identicalInitial||Math.abs(cargo[0]-cargo[1])<.1)throw new Error('No valid visible comparison: '+JSON.stringify(proof));log.rounds.push(proof);await p.locator('#compare').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,round+'-compare.png')});}
async function keep(){const response=p.waitForResponse(r=>r.url().endsWith('/install'));await p.locator('#install').click();const result=await(await response).json();await p.waitForFunction(()=>document.querySelector('#message').textContent.startsWith('Kept mechanic'));return result.version}
try{await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>document.querySelector('#revision').textContent.includes('revision'));
await play();await ask('Add a release condition to the existing Cargo connection: when Player speed exceeds 0.5, detach Cargo and leave it where it was. Keep the current slow pickup conditions and Player movement.','01');
await p.locator('#try-new').click();await play();await p.screenshot({path:path.join(out,'01-try.png')});log.rounds[0].installedVersion=await keep();
await play();await ask('Remove the release rule: moving quickly must no longer drop Cargo. Only acquiring Cargo should require a slow approach. Leave Player movement unchanged.','02');
await p.locator('#try-new').click();await play();await p.screenshot({path:path.join(out,'02-try.png')});log.rounds[1].installedVersion=await keep();
const rollback=p.waitForResponse(r=>r.url().endsWith('/rollback'));await p.locator('#undo').click();log.rollback=await(await rollback).json();
console.log(JSON.stringify({out,rounds:log.rounds.map(r=>({base:r.base_version,installed:r.installedVersion,cargo:r.cargo,identicalInput:r.identicalInput,identicalInitial:r.identicalInitial})),rollback:log.rollback.version,errors:log.errors}));
}catch(e){log.failure=e.message;console.error(e.message);await p.screenshot({path:path.join(out,'failure.png')});process.exitCode=1}
finally{await Promise.allSettled(pending);fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(log,null,2));await context.close();await browser.close()}
})();
